FROM nginx:alpine
RUN sed -i 's/http {/http {\n    server_tokens off;/g' /etc/nginx/nginx.conf
RUN sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf
RUN addgroup -g 1000 webgroup && \
    adduser -u 1000 -D -S -G webgroup webuser && \
    mkdir -p /var/lib/nginx && \
    chown -R webuser:webgroup /var/cache/nginx /var/run /var/log/nginx /usr/share/nginx/html /etc/nginx/conf.d /var/lib/nginx
USER webuser
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
